### PR TITLE
Chore upgrade docs

### PR DESCRIPTION
**Pull request by josheleonard**
Upgrades Docusaurus to version 3

### CODE REVIEW

**Comment by diracdeltas** [comment]
Could you add `yarn audit` to the build-publish action or some other pre-merge action? so it's easy to see if new deps fail the audit

**Comment by josheleonard** [comment]
@diracdeltas , added the audit step to the GH actions flow. The audit is failing now though

**Comment by josheleonard** [comment]
@diracdeltas , The `yarn audit` findings are now fixed

**Comment by josheleonard** [comment]
@diracdeltas , ok to merge this?

**Review by kdenhartog — APPROVED** [review]
Lgtm

**Pull request merged**
